// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45vkYZMaH1MgoL9D0ReeINNpbeONki9Q',
    appId: '1:429622645122:web:a0d850fdc9df625eaabf9b',
    messagingSenderId: '429622645122',
    projectId: 'breifai-3b5b8',
    authDomain: 'breifai-3b5b8.firebaseapp.com',
    storageBucket: 'breifai-3b5b8.firebasestorage.app',
    measurementId: 'G-D2EYF6V4EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFv87MZVb3mx5yggIokCMe9ybPX5xJ00M',
    appId: '1:429622645122:android:3b684404405723edaabf9b',
    messagingSenderId: '429622645122',
    projectId: 'breifai-3b5b8',
    storageBucket: 'breifai-3b5b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkVel08ZMYWqGFz2DObdV6cAv4VtP9FE8',
    appId: '1:429622645122:ios:304a24e5878ddd1eaabf9b',
    messagingSenderId: '429622645122',
    projectId: 'breifai-3b5b8',
    storageBucket: 'breifai-3b5b8.firebasestorage.app',
    iosBundleId: 'com.example.briefAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkVel08ZMYWqGFz2DObdV6cAv4VtP9FE8',
    appId: '1:429622645122:ios:304a24e5878ddd1eaabf9b',
    messagingSenderId: '429622645122',
    projectId: 'breifai-3b5b8',
    storageBucket: 'breifai-3b5b8.firebasestorage.app',
    iosBundleId: 'com.example.briefAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45vkYZMaH1MgoL9D0ReeINNpbeONki9Q',
    appId: '1:429622645122:web:b50239ec6d26b16baabf9b',
    messagingSenderId: '429622645122',
    projectId: 'breifai-3b5b8',
    authDomain: 'breifai-3b5b8.firebaseapp.com',
    storageBucket: 'breifai-3b5b8.firebasestorage.app',
    measurementId: 'G-YX892NTCYJ',
  );
}
